### PR TITLE
var cleanup, status_bar fix

### PR DESCRIPTION
**Pull request by m-1-k-3**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Bug fix

* **What is the current behavior?** (You can also link to an open issue here)

helpers local/export vars
status bar issues

* **What is the new behavior (if this is a feature change)? If possible add a screenshot.**

fixed vars
status bar should work better - closes https://github.com/e-m-b-a/emba/issues/461
closes https://github.com/e-m-b-a/emba/issues/1070

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by m-1-k-3** [comment]
ping @torabi12

**Comment by torabi12** [comment]
I changed the terminal size many times during the scan, it was working fine in small:

kép

in big:
kép

Rarely the refresh was not perfect:
kép

But after resizing again it was ok.
At the end was like this:

kép

In summary the behaviour is much better than before with status bar. Thank you!

**Comment by m-1-k-3** [comment]
@torabi12 should also address https://github.com/e-m-b-a/emba/issues/1070

**Comment by torabi12** [comment]
> @torabi12 should also address #1070

I can check the #1070 tomorrow I hope.
May I try again the status bar test today?

**Comment by m-1-k-3** [comment]
status bar looks good to me. The artefacts are looking quite small. If they do not destroy the rest of the behavior it is fine for me

**Comment by torabi12** [comment]
> status bar looks good to me. The artefacts are looking quite small. If they do not destroy the rest of the behavior it is fine for me

Yes, it was appropriate. Thanks again!

**Review by HoxhaEndri — APPROVED** [review]

**Pull request merged**
