### PR TITLE
Massive SBOM improvements

### LINKED ISSUE #1310: Complex binary names aren't parsed correctly
**Describe the bug**
When you have a binary that has more complex characters or parts than just `binary:version`, then EMBA doesn't fully know how to parse it.

i.e with a line like so in `s116_qemu_version_detection`:
`/usr/sbin/ntpdate;ntpdate;ntpdate 4.2.8p15;ntp:ntp:4.2.8:p15;unknown;1;`

The logic in EMBA will treat this not as an NTP binary of any kind, but like the binary `4.2.8` with a version of `p15`.

**To Reproduce**
1. EMBA installation of tag 1.4.2
2. Use the firmware available here: NTP should be available on most OpenWRT images
3. Start EMBA with the following parameters: Any, as long as it runs the package compilation & cve compilation modules
4. See bug

**Expected behavior**
It should be creating CVEs for the NTP binary, NOT a `4.2.8` binary that doesn't exist.

**Screenshots**
N/A

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04, AWS EC2 instance
- EMBA version: v1.4.2
- Installation method: default with up to date docker image

**Priority issue**
Are you already a [Sponsor]? - N

**Additional context**
N/A

[Sponsor]: https://github.com/sponsors/e-m-b-a

### LINKED ISSUE #1311: How to reduce sbom detection time
**Is your feature request related to a problem? Please describe.**
How to reduce sbom detection time
I just want to perform sbom detection and output sbom files, but its detection time is very long, especially for S09_firmware_mase-version_check, which takes a lot of time. Do I have any other ways to improve efficiency? Thank you

image

### LINKED ISSUE #1333: Docker not installing
Downloaded Kali Linux: kali-linux-2023.3-installer-amd64.iso
Set to 8 processors 16GB Memory
After initial install then did: apt full-update -y
Reboot

Did the GIT command to download the EMBA Installer.
./installer.sh -d

Once done I tried to do: ./emba -U

Get    the error: 
Some dependencies are missing - please check your installation
                                                                                                                                 
To install all needed dependencies, run 'sudo ./installer.sh'.                                                                   
Learn more about the installation on the EMBA wiki: https://github.com/e-m-b-a/emba/wiki/installation                            

Looks like docker is missing.

└─# apt install docker   
Package docker is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  wmdocker

Error: Package 'docker' has no installation candidate

### PR DESCRIPTION
**Pull request by m-1-k-3**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Feature

* **What is the current behavior?** (You can also link to an open issue here)

Just little SBOMdorado

* **What is the new behavior (if this is a feature change)? If possible add a screenshot.**

More SBOMdorado
closes #1310 
closes #1311 
closes #1333 
addresses also #443

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

Support the following sources for SBOM generation:
- [x] Binaries and libraries (as before via module s09 - excluded from quick sbom profile)
- [x] Linux Kernel (via module S24 - could take quite long)
- [x] Linux Kernel (extracted from kernel modules - module s25)
- [x] Kernel modules (via module s25)
- [x] RPM package management system
- [x] Debian package management system
- [x] OpenWRT Package management system
- [x] Python PIP package management system
- [x] Python requirements files
- [x] RPM packages
- [x] DEB packages
- [x] FreeBSD pkg packages
- [x] Java archives (jar, war)
- [x] Alpine APK
- [x] Rust (cargo.lock)
- [x] Ruby (gem)
- [x] Windows binaries (exif data)
- [x] Python poetry.lock
- [x] Linux distribution identification (via module s06)
- [x] Windows binary extraction and analysis

* **Other information**:

~The implementation state is somehow incomplete. Some of the parsers already have CPE's and PURLs, authors, licenses and so on. On the other hand there are others that are lacking most of this data.~

See also https://github.com/e-m-b-a/emba/wiki/SBOM-environment

### CODE REVIEW

**Comment by m-1-k-3** [comment]
Massive updates ... please test

**Comment by m-1-k-3** [comment]
docker base image v1.4.2f with pixd fix is available

**Comment by m-1-k-3** [comment]
This will also close #1310

**Comment by m-1-k-3** [comment]
closes #1311

**Comment by m-1-k-3** [comment]
This beast is now ready for a first public test. Please go ahead and report all the things that are looking weird or are not working as expected.
@busby666 @torabi12 could you support the testing process?

Happy hunting :)

**Comment by m-1-k-3** [comment]
Includes windows binary extraction and SBOM analysis *w00tw00t*

**Comment by torabi12** [comment]
This section of the install was not OK:

kép

**Comment by m-1-k-3** [comment]
> This section of the install was not OK:

hmmm, what is your Kali base image you are using and which section is this?

**Comment by torabi12** [comment]
I use Kali 2024.3 in VMware Workstation Pro 17.6.1

**Comment by m-1-k-3** [comment]
> I use Kali 2024.3 in VMware Workstation Pro 17.6.1

ok, I will do another install on a plain 2024.3

**Comment by torabi12** [comment]
Maybe something is wrong on my side, but it is not an old VM. I will check again tomorrow with a brand new Kali.

**Comment by m-1-k-3** [comment]
I had the same installation output but the installation finished and dep check was ok. Currently, I run a test with DIR300 to check if everything works.

**Comment by m-1-k-3** [comment]
My testrun on a 2024.3 and 2024-W41 was fine.

**Comment by torabi12** [comment]
> My testrun on a 2024.3 and 2024-W41 was fine.

I reinstalled my host machine last night and it took such a long time to get back everything. :(
Win 11 24H2, maybe not the best choice at the begining, but wanted to see the latest version.

**Pull request merged**
