### PR TITLE
Red warnings - install crackmapexec through pipx

### PR DESCRIPTION
**Pull request by HoxhaEndri**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Removes red warning during installation

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)? If possible add a screenshot.**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by m-1-k-3** [comment]
I'm not sure this is the way to solve dep issues. Let's move this to a draft PR for now and evaluate further possibilities

**Comment by m-1-k-3** [comment]
Closing ... see comment here https://github.com/e-m-b-a/emba/issues/568

**Comment by m-1-k-3** [comment]
Could you please create a separate PR for the changes in S115? Thanks

**Comment by HoxhaEndri** [comment]
The last commit 'ignore named pipe' has already been merged in emba with a separate PR: https://github.com/e-m-b-a/emba/pull/601.  I mistakenly forgot to create a new branch, in order to create a separate PR, that's why it is also here.

**Pull request closed without merging**
