### PR TITLE
Virustotal and hash searcher module

### PR DESCRIPTION
**Pull request by m-1-k-3**
This PR includes the following changes:
* P03 - virustotal upload of the firmware (needs a api key in config/vt_api_key.txt)
* new switch -o to enable online checks like P03
* cleanup of versions
* some new versions from the Netgear DGN2200 used in MS blog post (https://www.microsoft.com/security/blog/2021/06/30/microsoft-finds-new-netgear-firmware-vulnerabilities-that-could-lead-to-identity-theft-and-full-system-compromise/)
* Fixed a bad bug that was introduced during RTOS cleanup last week
* P05 is now much faster
* pre-checkers are now threaded (you can enable or disable it via the new header "export PRE_THREAD_ENA=1")
* updated regex for s45 password hashes
* new s107 which searches all files for pw hashes

### CODE REVIEW

**Comment by p4cx** [comment]
General discussion:
At the moment we are telling the users of emba, that they should disable the internet access for emba, because we are emulation executables without knowing, what they are doing. 
With -o we have to allow internet access for the full emba run - this doesn't sounds optimal. But at the moment, I don't have an idea for an elegant solution to make emba safe to use with internet access. Maybe we can configure emba at some modules, like the emulation, that it should somehow disable internet access.

**Comment by m-1-k-3** [comment]
As this is an option the user has to enable with -o I don't see a problem. All in all we should recommend to disable Internet access with some exceptions like virustotal.

**Comment by p4cx** [comment]
I don't know, I am not fully satisfied with this solution. If I don't set -o, then it is possible for old modules or other processes (like emulated programs) to access the internet. It it fine for now, but maybe we should try to add an blocker for the internet at least in the docker container, if the -o isn't set.

**Comment by m-1-k-3** [comment]
Currently everything is able to access the internet and the user has to take care to secure his environment. The idea to  secure the docker is a possibility to make it a bit harder and we should evaluate this. But as everything runs as root it is easy to disable iptables rules in the container. At the end, we could make it a bit harder for an attacker but the user needs to take care on the emba host.

**Comment by p4cx** [comment]
Yes, that is not optimal. But if I disable the internet access in my virtual machine, then -o also can't access the internet. But you are right, the user has to take the risk, if he wants to use modules with internet access.

**Review by p4cx — APPROVED** [review]

**Comment by p4cx** [comment]
Nice work 👍

**Pull request merged**
