### PR TITLE
UX: Change the install prompt choices to match other installers and common package managers

### PR DESCRIPTION
**Pull request by nightlark**
Changes the install prompt text from `(y/Y)` to `(y/N)`. Default behavior by just hitting enter seems to be not installing.

### CODE REVIEW

**Comment by p4cx** [comment]
To install, you have to enter `y` or `Y` and then press enter. Without entering a character it acts like, if there was a wrong input (not `y` or `Y`).

**Comment by nightlark** [comment]
This is a UX bug then -- when you go to install a package with most package managers (or installers) they give you a prompt with a variant of `y/n` where the capitalized letter is the default behavior if you don't type anything.

**Comment by nightlark** [comment]
e.g. with apt:
```shell
> sudo apt-get install binutils
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  binutils-common binutils-x86-64-linux-gnu libbinutils
Suggested packages:
  binutils-doc
The following packages will be upgraded:
  binutils binutils-common binutils-x86-64-linux-gnu libbinutils
4 upgraded, 0 newly installed, 0 to remove and 173 not upgraded.
Need to get 2527 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n]
```

**Comment by p4cx** [comment]
Thanks for your detailed explanation. I didn't think about it at all and didn't notice it. You're right! Thank you for your contribution to emba.

**Review by p4cx — APPROVED** [review]

**Pull request merged**
