### PR TITLE
Sudoers check

### PR DESCRIPTION
**Pull request by m-1-k-3**
sudo-parser.pl included to S50 module

image

Source:
https://twitter.com/timb_machine/status/1373341629516558352?s=20
https://github.com/CiscoCXSecurity/sudo-parser/blob/master/sudo-parser.pl

Thx to @timb-machine

### CODE REVIEW

**Comment by p4cx** [comment]
There seems to be a bug within the parser:

image

**Comment by m-1-k-3** [comment]
started emba with sudo? I got the failure if I used the parser as non root

**Comment by p4cx** [comment]
No, I didn't because it is only a file parser. It shouldn't need sudo to read the file, but I believe that our use case with the sudoers-parser is new: The files no longer need root to be read. But I will check it for now and if there will be an update of the parser, we can change our code back to a non-sudo setup.

**Comment by m-1-k-3** [comment]
Opened an issue https://github.com/CiscoCXSecurity/sudo-parser/issues/8

**Review by p4cx — APPROVED** [review]

**Pull request merged**
